#!/usr/bin/env python3
"""
Reproduce all figures from saved NPZ data file.

This script loads the energy_analysis_data.npz file and recreates all plots
exactly as they were generated by plot_binary_energy_analysis.py.

Usage:
    python reproduce_figures_from_npz.py [npz_filename]
    
If no filename is provided, defaults to 'energy_analysis_data.npz'
"""

import numpy as np
import matplotlib.pyplot as plt
import sys

plt.rcParams['text.usetex'] = True
plt.rcParams['font.family'] = 'serif'
plt.rcParams["legend.frameon"] = False
# Publication-ready font sizes
plt.rcParams['font.size'] = 20
plt.rcParams['axes.labelsize'] = 22
plt.rcParams['axes.titlesize'] = 28
plt.rcParams['xtick.labelsize'] = 22
plt.rcParams['ytick.labelsize'] = 22
plt.rcParams['legend.fontsize'] = 18   
plt.rcParams['figure.titlesize'] = 28


if len(sys.argv) > 1:
    npz_filename = sys.argv[1]
else:
    npz_filename = 'energy_analysis_data.npz'

print("="*70)
print("Reproducing Figures from NPZ Data")
print("="*70)
print(f"Loading data from: {npz_filename}")

try:
    data = np.load(npz_filename, allow_pickle=True)
except FileNotFoundError:
    print(f"ERROR: File '{npz_filename}' not found!")
    print("Please run plot_binary_energy_analysis.py first to generate the data file.")
    sys.exit(1)

snapshots = data['snapshots']
K_tots = data['K_tots']
K_unweighted = data['K_unweighted']
K_tots_erg = data['K_tots_erg']
outflow_rates = data['outflow_rates']
outflow_rates_ergs = data['outflow_rates_ergs']
n_particles = data['n_particles']
depletion_timescales = data['depletion_timescales']
sigma_h_kms = float(data['sigma_h_kms'])
dt_myr = float(data['dt_myr'])
component = str(data['component'])

final_time_myr = 24437.659952727288
if len(snapshots) > 0:
    time_myr = np.linspace(0.0, final_time_myr, len(snapshots))
    time_gyr = time_myr / 1000.0
else:
    time_myr = np.array([])
    time_gyr = np.array([])

print(f"Loaded data for {len(snapshots)} snapshots")
print(f"Component filter: {component}")
print(f"σ_h = {sigma_h_kms} km/s")
print(f"dt_myr = {dt_myr} Myr")
if len(time_gyr) > 0:
    print(f"Time range: {time_gyr[0]:.4f} - {time_gyr[-1]:.4f} Gyr")
    print(f"Final time (snapshot {snapshots[-1]}): {final_time_myr/1000.0:.4f} Gyr")
print("="*70)

MSUN_G = 1.98847e33
KM_TO_CM = 1.0e5
SEC_PER_GYR = 3.15576e16

print("\nGenerating plots...")
print("-" * 70)

def plot_energy_distributions():
    n_snapshots = len(snapshots)
    ncols = min(3, n_snapshots)
    nrows = (n_snapshots + ncols - 1) // ncols
    fig, axes = plt.subplots(nrows, ncols, figsize=(5*ncols, 4*nrows))
    if n_snapshots == 1:
        axes = [axes]
    else:
        axes = axes.flatten()
    
    for idx, snap in enumerate(snapshots):
        ax = axes[idx]
        
        energies_key = f'energies_snap{snap}'
        masses_key = f'masses_snap{snap}'
        weights_key = f'weights_snap{snap}'
        
        if energies_key not in data:
            ax.text(0.5, 0.5, f'Snapshot {snap}\n(no data)', 
                   ha='center', va='center', transform=ax.transAxes)
            continue
        
        energies = data[energies_key]
        masses = data[masses_key]
        weights = data[weights_key]
        
        if len(energies) == 0:
            ax.text(0.5, 0.5, f'Snapshot {snap}\n(no data)', 
                   ha='center', va='center', transform=ax.transAxes)
            continue
        
        valid_mask = (energies > 0) & np.isfinite(energies) & np.isfinite(weights) & np.isfinite(masses)
        energies_valid = energies[valid_mask]
        weights_valid = weights[valid_mask]
        masses_valid = masses[valid_mask]
        
        if len(energies_valid) == 0:
            ax.text(0.5, 0.5, f'Snapshot {snap}\n(no valid data)', 
                   ha='center', va='center', transform=ax.transAxes)
            continue
        
        emin = energies_valid.min()
        emax = energies_valid.max()
        if emin > 0 and emax > emin:
            bins = np.logspace(np.log10(emin), np.log10(emax), 30)
            weights_clipped = np.clip(weights_valid * masses_valid, 0, 1e100)
            ax.hist(energies_valid, bins=bins, weights=weights_clipped, 
                   alpha=0.7, edgecolor='black', label='Weighted')
        else:
            bins = np.linspace(emin, emax, 30)
            weights_clipped = np.clip(weights_valid * masses_valid, 0, 1e100)
            ax.hist(energies_valid, bins=bins, weights=weights_clipped, 
                   alpha=0.7, edgecolor='black', label='Weighted')
        
        if emin > 0 and emax > emin:
            ax.set_xscale('log')
        ax.set_xlabel(r'$|E|$ (dimensionless)', fontsize=22)
        ax.set_ylabel(r'Weighted count ($M_\odot \times x$)', fontsize=22)
        ax.set_title(f'Snapshot {snap}', fontsize=28)
        ax.grid(alpha=0.3)
        
        K_tot = K_tots[idx]
        ax.text(0.05, 0.95, f'K_tot = {K_tot:.2e}', 
               transform=ax.transAxes, va='top', fontsize=10,
               bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    for idx in range(n_snapshots, len(axes)):
        axes[idx].set_visible(False)
    
    plt.tight_layout()
    plt.savefig('energy_distributions_by_snapshot.png', dpi=150)
    print("Saved energy_distributions_by_snapshot.png")
    plt.show()

def plot_total_kinetic_energy():
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))
    
    ax1.plot(time_myr, K_tots, '-', linewidth=2, markersize=8)
    ax1.set_xlabel(r'Time (Myr)', fontsize=22)
    ax1.set_ylabel(r'$K_{\rm tot}$ (dimensionless, $M_\odot \times x$)', fontsize=22)
    ax1.set_title(f'Total Kinetic Energy Evolution ({component})', fontsize=28)
    ax1.grid(alpha=0.3)
    
    ax2.plot(time_myr, K_tots_erg, '-', linewidth=2, markersize=8, color='red')
    ax2.set_xlabel(r'Time (Myr)', fontsize=22)
    ax2.set_ylabel(r'$K_{\rm tot}$ (erg)', fontsize=22)
    ax2.set_title(rf'Total Kinetic Energy ($\sigma_h = {sigma_h_kms}$ km s$^{{-1}}$)', fontsize=28)
    ax2.grid(alpha=0.3)
    ax2.ticklabel_format(style='scientific', axis='y', scilimits=(0,0))
    
    plt.tight_layout()
    plt.savefig('total_kinetic_energy_evolution.png', dpi=150)
    print("Saved total_kinetic_energy_evolution.png")
    plt.show()

def plot_energy_outflow_rate():
    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(10, 8))
    
    ax1.plot(time_myr, outflow_rates, '-', linewidth=2, markersize=8, color='green')
    ax1.set_xlabel(r'Time (Myr)', fontsize=22)
    ax1.set_ylabel(r'$\dot{E}_{\rm out}$ (dimensionless, $M_\odot \times x$ Gyr$^{-1}$)', fontsize=22)
    ax1.set_title(f'Energy Outflow Rate ({component})', fontsize=28)
    ax1.grid(alpha=0.3)
    
    ax2.plot(time_myr, outflow_rates_ergs, '-', linewidth=2, markersize=8, color='darkgreen')
    ax2.set_xlabel(r'Time (Myr)', fontsize=22)
    ax2.set_ylabel(r'$\dot{E}_{\rm out}$ (erg s$^{-1}$)', fontsize=22)
    ax2.set_title(rf'Energy Outflow Power ($\sigma_h = {sigma_h_kms}$ km s$^{{-1}}$)', fontsize=28)
    ax2.grid(alpha=0.3)
    ax2.ticklabel_format(style='scientific', axis='y', scilimits=(0,0))
    
    plt.tight_layout()
    plt.savefig('energy_outflow_rate.png', dpi=150)
    print("Saved energy_outflow_rate.png")
    plt.show()

def create_summary_plot():
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    
    ax = axes[0, 0]
    K_tots_erg_scaled = K_tots_erg / 1e60
    ax.plot(time_gyr, K_tots_erg_scaled, '-', linewidth=2, markersize=8, color='blue')
    ax.set_xlabel(r'Time (Gyr)', fontsize=22)
    ax.set_ylabel(r'$K_{\rm tot}$ ($\times 10^{60}$ erg)', fontsize=22)
    ax.set_title('Total Kinetic Energy', fontsize=28)
    ax.grid(alpha=0.3)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:.1f}'))
    ax.tick_params(labelsize=22)
    if len(time_gyr) > 0 and len(K_tots_erg_scaled) > 0:
        x_min, x_max = time_gyr.min(), time_gyr.max()
        y_min, y_max = K_tots_erg_scaled.min(), K_tots_erg_scaled.max()
        ax.set_xlim(x_min, x_max)
        ax.set_ylim(y_min-(y_max-y_min)*0.1, y_max+(y_max-y_min)*0.1)
    
    ax = axes[0, 1]
    outflow_rates_ergs_scaled = outflow_rates_ergs / 1e47
    ax.plot(time_gyr, outflow_rates_ergs_scaled, '-', linewidth=2, markersize=8, color='red')
    ax.set_xlabel(r'Time (Gyr)', fontsize=22)
    ax.set_ylabel(r'$\dot{E}_{\rm out}$ ($\times 10^{47}$ erg s$^{-1}$)', fontsize=22)
    ax.set_title('Energy Outflow Rate', fontsize=28)
    ax.grid(alpha=0.3)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:.1f}'))
    ax.tick_params(labelsize=22)
    if len(time_gyr) > 0 and len(outflow_rates_ergs_scaled) > 0:
        x_min, x_max = time_gyr.min(), time_gyr.max()
        y_min, y_max = outflow_rates_ergs_scaled.min(), outflow_rates_ergs_scaled.max()
        ax.set_xlim(x_min, x_max)
        ax.set_ylim(y_min-(y_max-y_min)*0.1, y_max+(y_max-y_min)*0.1)
    
    ax = axes[1, 0]
    ax.plot(time_gyr, depletion_timescales, '-', linewidth=2, markersize=8, color='purple')
    ax.set_xlabel(r'Time (Gyr)', fontsize=22)
    ax.set_ylabel(r'$\xi=K_{\rm tot}/\dot{E}_{\rm out}$ (Gyr)', fontsize=22)
    ax.set_title('Energy Depletion Timescale', fontsize=28)
    ax.grid(alpha=0.3)
    ax.tick_params(labelsize=22)
    if len(time_gyr) > 0 and len(depletion_timescales) > 0:
        valid_mask = np.isfinite(depletion_timescales)
        if np.any(valid_mask):
            valid_time = time_gyr[valid_mask]
            valid_tdep = depletion_timescales[valid_mask]
            x_min, x_max = valid_time.min(), valid_time.max()
            y_min, y_max = valid_tdep.min(), valid_tdep.max()
            ax.set_xlim(x_min, x_max)
            ax.set_ylim(y_min-(y_max-y_min)*0.1, y_max+(y_max-y_min)*0.1)
    
    ax = axes[1, 1]
    n_particles_scaled = n_particles / 1e5
    ax.plot(time_gyr, n_particles_scaled, '-', linewidth=2, markersize=8, color='green')
    ax.set_xlabel(r'Time (Gyr)', fontsize=22)
    ax.set_ylabel(r'Number of particles ($\times 10^5$)', fontsize=22)
    ax.set_title(f'Particle Count', fontsize=28)
    ax.grid(alpha=0.3)
    ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda x, p: f'{x:.1f}'))
    ax.tick_params(labelsize=22)
    if len(time_gyr) > 0 and len(n_particles_scaled) > 0:
        x_min, x_max = time_gyr.min(), time_gyr.max()
        y_min, y_max = n_particles_scaled.min(), n_particles_scaled.max()
        ax.set_xlim(x_min, x_max)
        ax.set_ylim(y_min-(y_max-y_min)*0.1, y_max+(y_max-y_min)*0.1)
    
    # plt.suptitle(f'Energy Budget Summary (σ_h = {sigma_h_kms} km/s)', fontsize=14, y=0.995)
    plt.tight_layout()
    plt.savefig('energy_summary.png', dpi=150)
    print("Saved energy_summary.png")
    plt.show()

# plot_energy_distributions()
# plot_total_kinetic_energy()
# plot_energy_outflow_rate()
create_summary_plot()

print("-" * 70)
print("All figures reproduced successfully!")
print("\nGenerated files:")
print("  - energy_distributions_by_snapshot.png")
print("  - total_kinetic_energy_evolution.png")
print("  - energy_outflow_rate.png")
print("  - energy_summary.png")

